### ISSUE TITLE
IE11 Compatibility 

### ISSUE THREAD

**Issue by michalexvr** [creativetimofficial/ct-vue-light-bootstrap-dashboard-pro#19]
Hello,

The template does not deploy properly in IE11. It freezes in the first slot of left menu.

How can i solve this?

Thanks a lot.

Regards

**Comment by cristijora** [comment]
Hi @michalexvr 
I opened an issue some time ago with detailed code/steps in order to make it work on IE here #3 
You just have to add some missing methods like `Array.find` which are not available on IE.
Usually such pollyfills can be found on MDN https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#polyfill
on each individual method.

Hope this helps.
