### ISSUE TITLE
CSS differences between Vue light pro and all other Light Dashboard variants

### ISSUE THREAD

**Issue by parigi-n** [creativetimofficial/ct-vue-light-bootstrap-dashboard-pro#22]
Hello,

So i just bought the pro version if Vue Light Boostrap after using the free version and spotted some differences in the theme while doing the upgrade.

For example here is a screenshot of one of my page from Vue Light bootstrap dashboard free

![vue-light-boostrap-normal](https://user-images.githubusercontent.com/20981240/40718834-6fdfed22-63df-11e8-983f-cfc8b6c4aa71.png)

Now in Pro : 
![vue-light-boostrap-pro](https://user-images.githubusercontent.com/20981240/40718833-6fcde97e-63df-11e8-8c95-5992438f3e56.png)
(Bigger font weight, filled buttons etc)

At first i thought i was causing the bug, but it behave exactly like this in the preview page https://demos.creative-tim.com/vue-light-bootstrap-dashboard-pro

With the typography page you can see the different font weight between the pro version and all other variants :

[Vue Light Bootstrap Pro](https://demos.creative-tim.com/vue-light-bootstrap-dashboard-pro/#/components/typography)

[Light Bootstrap Pro Angular2](https://demos.creative-tim.com/light-bootstrap-dashboard-pro-angular2/components/typography)
[Light Bootstrap Pro React](https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/components/typography)
[Vue Light Bootstrap (free)](https://demos.creative-tim.com/vue-light-bootstrap-dashboard/#/admin/typography)

I would like to know if it's on purpose or it's a bug ?
If it's on purpose, how can i reverse to the style of the free/react/angular version ?

**Comment by cristijora** [comment]
Hello @parigi-n 
Really sorry for not responding. For some reason, due to many github notifications, I missed this one :(
I will do an update pretty soon with various fixes and look into this as well. 

Indeed, the font seems slightly different. You can cross check if in `index.html` the font is this one 
`https://fonts.googleapis.com/css?family=Roboto:400,700,300`

As for buttons, this was a change from free to PRO. You can use `btn-outline` along with other css classes to change the button look so it looks like in free version.

**Comment by parigi-n** [comment]
Thanks for the tricks ! It will do the job
Keep up the good work
