### ISSUE TITLE
Internet Explorer compatibility

### ISSUE THREAD

**Issue by cristijora** [creativetimofficial/ct-vue-light-bootstrap-dashboard-pro#3]
Currently there are some issues with the sidebar not being shown on IE.
https://d.pr/i/r06AIM 

This is mainly due to the fact that the Sidebar plugin uses some array methods like `find` which are not supported on IE. To get around the issue, a polyfill file can be created and referenced in the main js entry or in `light-bootstrap-main.js`
https://gist.github.com/cristijora/f52a1b7cb5c249bfb5f4b1569adb82f3

**Comment by spevilgenius** [comment]
This works great for the side panel! However, in IE11 I still get an error with the chartist.js for the charts. Unable to get property 'querySelectorAll' of undefined or null reference. This is not a showstopper per se because I can use different charts like highcharts. Just would like to see the included charts work as well in case I need them.

**Comment by cristijora** [comment]
@spevilgenius I will look into that since I want to add IE support in the next update
